# Generated by Django 3.1.4 on 2021-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('examiner_notes', models.TextField()),
                ('scan_datetime', models.DateTimeField()),
                ('scan_location', models.CharField(max_length=50)),
                ('scan_operator', models.CharField(max_length=50)),
                ('scan_reason', models.CharField(max_length=50)),
            ],
        ),
    ]
