# Generated by Django 3.1.4 on 2021-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phemelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='scan_copy',
            field=models.FileField(upload_to='scans/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
